kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: pipeline-n3
  labels:
    app: pipeline-n3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pipeline-n3
        version: v1
    spec:
      containers:
      - name: pipeline-node
        image: ykoyfman/pipeline_node
        imagePullPolicy: Always
        env:
        - name: NEXT_STEP_URL
          value: ""
        - name: WORK_TIME
          value: "2"
        - name: ERROR_RATE
          value: "0.05"          
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: pipeline-n3
  labels:
    app: pipeline-n3
spec:
  selector:
    app: pipeline-n3
  ports:
    - port: 9080
      name: http

---
