kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: pipeline-n1
  labels:
    app: pipeline-n1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pipeline-n1
        version: v1
    spec:
      containers:
      - name: pipeline-node
        image: ykoyfman/pipeline_node.zip
        resources:
          limits:
            cpu: "0.1"
          requests:
            cpu: "0.1"
        imagePullPolicy: Always
        env:
        - name: NEXT_STEP_URL
          value: "http://pipeline-n2:9080/pipeline-node/resources/process"
        - name: WORK_TIME
          value: "2"
        - name: ERROR_RATE
          value: "0.05"
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: pipeline-n1
  labels:
    app: pipeline-n1
spec:
  selector:
    app: pipeline-n1
  ports:
    - port: 9080
      name: http

---
